USE cs157aproject;

CREATE VIEW `ADMIN_VIEW` AS 
  SELECT m.MARKET_ID, m.MARKET_NAME, v.VENDOR_ID, v.VENDOR_NAME, v.VENDOR_PHONE, v.VENDOR_MARKET_ID, s.STALL_ID, s.STALL_NAME, s.STALL_FEE, s.STALL_VENDOR_ID
  FROM `MARKET` m 
  INNER JOIN `VENDOR` v ON m.MARKET_ID = v.VENDOR_MARKET_ID
  INNER JOIN `STALL` s on v.VENDOR_ID = s.STALL_VENDOR_ID;

CREATE VIEW `INSPECTOR_VIEW` AS 
  SELECT v.VENDOR_ID, v.VENDOR_NAME, v.VENDOR_PHONE, s.STALL_ID, s.STALL_NAME, s.STALL_VENDOR_ID, i.INSPECTION_ID, i.INSPECTION_STALL_ID, i.INSPECTION_DATE, i.INSPECTION_RESULT
  FROM `VENDOR` v
  INNER JOIN `STALL` s ON v.VENDOR_ID = s.STALL_VENDOR_ID
  INNER JOIN `INSPECTION` i on s.STALL_ID = i.INSPECTION_STALL_ID;

CREATE VIEW `VENDOR_VIEW` AS 
  SELECT v.VENDOR_ID, v.VENDOR_NAME, v.VENDOR_PHONE, su.SUPPLIER_ID, su.SUPPLIER_NAME, su.SUPPLIER_PHONE, su.SUPPLIER_VENDOR_ID, s.STALL_ID, s.STALL_NAME, s.STALL_FEE, s.STALL_VENDOR_ID, s.STALL_PRODUCT_THROUGHPUT, s.STALL_MONEY_THROUGHPUT, i.INSPECTION_ID, i.INSPECTION_STALL_ID, i.INSPECTION_DATE, i.INSPECTION_RESULT, p.PRODUCT_ID, p.PRODUCT_NAME, p.PRODUCT_STALL_ID, p.PRODUCT_CATEGORY_ID, p.PRODUCT_ON_HAND, c.CATEGORY_ID, c.CATEGORY_NAME, c.ALLERGY_PREVALENCE, c.ALLERGY_DESCRIPTION, c.ALLERGY_LABEL
  FROM `VENDOR` v
  INNER JOIN `SUPPLIER` su ON v.VENDOR_ID = su.SUPPLIER_VENDOR_ID
  INNER JOIN `STALL` s ON v.VENDOR_ID = s.STALL_VENDOR_ID
  INNER JOIN `INSPECTION` i on s.STALL_ID = i.INSPECTION_STALL_ID
  INNER JOIN `PRODUCT` p on s.STALL_ID = p.PRODUCT_STALL_ID
  INNER JOIN `CATEGORY` c on p.PRODUCT_CATEGORY_ID = c.CATEGORY_ID;

CREATE VIEW `SUPPLIER_VIEW` AS 
  SELECT su.SUPPLIER_ID, su.SUPPLIER_NAME, su.SUPPLIER_PHONE, su.SUPPLIER_VENDOR_ID, v.VENDOR_ID, v.VENDOR_NAME, v.VENDOR_PHONE, v.ADDRESS, v.STREET, v.STATE_ABBR, v.STATE_NAME, v.CITY, v.ZIP_CODE, s.STALL_ID, s.STALL_NAME, s.STALL_VENDOR_ID, p.PRODUCT_ID, p.PRODUCT_NAME, p.PRODUCT_STALL_ID, p.PRODUCT_ON_HAND
  FROM `SUPPLIER` su
  INNER JOIN `VENDOR` v ON su.SUPPLIER_VENDOR_ID = v.VENDOR_ID
  INNER JOIN `STALL` s ON v.VENDOR_ID = s.STALL_VENDOR_ID
  INNER JOIN `INSPECTION` i on s.STALL_ID = i.INSPECTION_STALL_ID
  INNER JOIN `PRODUCT` p on s.STALL_ID = p.PRODUCT_STALL_ID;

CREATE VIEW `TRANSPORTER_VIEW` AS 
  SELECT t.TRANSPORTER_ID, t.TRANSPORTER_NAME, t.TRANSPORTER_PHONE, o.ORDER_ID, o.ORDER_CUSTOMER_ID, o.DATE, o.QUANTITY, o.ORDER_TRANSPORTER_ID, c.CUSTOMER_ID, c.CUSTOMER_NAME, c.CUSTOMER_PHONE, c.ADDRESS, c.STREET, c.STATE_ABBR, c.STATE_NAME, c.CITY, c.ZIP_CODE
  FROM `TRANSPORTER` t
  INNER JOIN `CUSTOMER_LINE_ITEM` o ON t.TRANSPORTER_ID = o.ORDER_TRANSPORTER_ID
  INNER JOIN `CUSTOMER` c ON o.ORDER_CUSTOMER_ID = c.CUSTOMER_ID;

CREATE VIEW `CUSTOMER_VIEW` AS 
  SELECT c.CUSTOMER_ID, c.CUSTOMER_NAME, c.CUSTOMER_PHONE, c.CUSTOMER_SPENT, o.ORDER_ID, o.ORDER_CUSTOMER_ID, o.ORDER_PRODUCT_ID, o.DATE, o.QUANTITY, o.UNIT_PRICE, o.ORDER_TRANSPORTER_ID, t.TRANSPORTER_ID, t.TRANSPORTER_NAME, t.TRANSPORTER_PHONE, p.PRODUCT_ID, p.PRODUCT_NAME, p.PRODUCT_CATEGORY_ID, p.PRODUCT_ON_HAND, cat.CATEGORY_ID, cat.CATEGORY_NAME, cat.ALLERGY_PREVALENCE, cat.ALLERGY_DESCRIPTION, cat.ALLERGY_LABEL
  FROM `CUSTOMER` c
  INNER JOIN `CUSTOMER_LINE_ITEM` o ON c.CUSTOMER_ID = o.ORDER_CUSTOMER_ID
  INNER JOIN `TRANSPORTER` t ON o.ORDER_TRANSPORTER_ID = t.TRANSPORTER_ID
  INNER JOIN `PRODUCT` p on o.ORDER_PRODUCT_ID = p.PRODUCT_ID
  INNER JOIN `CATEGORY` cat on p.PRODUCT_CATEGORY_ID = cat.CATEGORY_ID;
